version: "3.8"
services:
  benchmark:
    build: .
    volumes:
      - .:/go/src
    links:
      - timescaledb
  timescaledb: 
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    #   # - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/tmp/db
    